import datetime
import os
# import tkinter as tk
# from tkinter import filedialog, ttk, messagebox
import json
import time
import unittest
from HtmlTestRunner import HTMLTestRunner
# from PIL import Image, ImageTk
import HtmlTestRunner
from selenium import webdriver
from selenium.webdriver import Keys, ActionChains
from selenium.webdriver.common.by import By
import logging
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from flask import Flask, render_template, request, jsonify, flash
# from flask_restful_swagger_3 import Api
# from flask_restful import Api, Resource
# from flask_restful_swagger_3 import swagger
from flasgger import Swagger
from Test_POSFunctionalPkg.TC_CashManagementTest import CashManagementTest
from Test_POSFunctionalPkg.TC_ParkBillTest import ParkBillTest
from Test_POSFunctionalPkg.TC_PointOfSaleTest import PointOfSaleTest
from Test_POSFunctionalPkg.TC_SalesHistoryTest import SalesHistoryTest
from Test_POSFunctionalPkg.TC_CloseTillTest import CloseTillTest
from Test_StoreAdminFunctionalPkg.TC_AddBrandTest import AddBrandTest
from Test_StoreAdminFunctionalPkg.TC_AddBusinessUnitTest import AddBusinessUnitTest
from Test_StoreAdminFunctionalPkg.TC_AddCustomersTest import AddCustomersTest
from Test_StoreAdminFunctionalPkg.TC_AddEmailTemplatesTest import AddEmailTemplatesTest
from Test_StoreAdminFunctionalPkg.TC_AddImageLibraryTest import AddImageLibraryTest
from Test_StoreAdminFunctionalPkg.TC_AddPOSOrdersTest import AddPOSOrdersTest
from Test_StoreAdminFunctionalPkg.TC_AddPricingRulesTest import AddPricingRulesTest
from Test_StoreAdminFunctionalPkg.TC_AddProductCatalogueTest import AddProductCatalogueTest
from Test_StoreAdminFunctionalPkg.TC_AddProductCategoryTest import AddProductCategoryTest
from Test_StoreAdminFunctionalPkg.TC_AddProductsTest import AddProductsTest
from Test_StoreAdminFunctionalPkg.TC_AddReturnReasonsTest import AddReturnReasonsTest
from Test_StoreAdminFunctionalPkg.TC_AddRFIDTagTest import AddRfidTagTest
from Test_StoreAdminFunctionalPkg.TC_AddStorageLocationTest import AddStorageLocationTest
from Test_StoreAdminFunctionalPkg.TC_AddSupplierCategoryTest import AddSupplierCategoryTest
from Test_StoreAdminFunctionalPkg.TC_AddSupplierTest import AddSupplierTest
from Test_StoreAdminFunctionalPkg.TC_AddTaxCategoryTest import AddTaxCategoryTest
from Test_StoreAdminFunctionalPkg.TC_AddTaxTest import AddTaxTest
from Test_StoreAdminFunctionalPkg.TC_AddTillTest import AddTillTest
from Test_StoreAdminFunctionalPkg.TC_AddUserTest import AddUserTest
from Test_StoreAdminFunctionalPkg.TC_AmountWiseNOBReportTest import AmountWiseNOBReportTest
from Test_StoreAdminFunctionalPkg.TC_CurrentStockReportTest import CurrentStockReportTest
from Test_StoreAdminFunctionalPkg.TC_DailySalesReportTest import DailySalesReportTest
from Test_StoreAdminFunctionalPkg.TC_HourlySalesReportTest import HourlySalesReportTest
from Test_StoreAdminFunctionalPkg.TC_InTransitStockReportTest import InTransitStockReportTest
from Test_StoreAdminFunctionalPkg.TC_InventoryAdjustmentReportTest import InventoryAdjustmentReportTest
from Test_StoreAdminFunctionalPkg.TC_LowStockReportTest import LowStockReportTest
from Test_StoreAdminFunctionalPkg.TC_PendingStockIssueReportTest import PendingStockIssueReportTest
from Test_StoreAdminFunctionalPkg.TC_POSSettingsTest import PosSettingsTest
from Test_StoreAdminFunctionalPkg.TC_ProductWastageReportTest import ProductWastageReportTest
from Test_StoreAdminFunctionalPkg.TC_PurchaseByProductReportTest import PurchaseByProductReportTest
from Test_StoreAdminFunctionalPkg.TC_PurchaseBySupplierReportTest import PurchaseBySupplierReportTest
from Test_StoreAdminFunctionalPkg.TC_PurchaseOrderTest import PurchaseOrderTest
from Test_StoreAdminFunctionalPkg.TC_PurchaseSummaryReportTest import PurchaseSummaryReportTest
from Test_StoreAdminFunctionalPkg.TC_PurchaseTaxSummaryReportTest import PurchaseTaxSummaryReportTest
from Test_StoreAdminFunctionalPkg.TC_QuickGoodsReceiptTest import QuickGoodsReceiptTest
from Test_StoreAdminFunctionalPkg.TC_QuickPurchaseOrderTest import QuickPurchaseOrderTest
from Test_StoreAdminFunctionalPkg.TC_QuickStockCountTest import QuickStockCountTest
from Test_StoreAdminFunctionalPkg.TC_QuickStockIssueTest import QuickStockIssueTest
from Test_StoreAdminFunctionalPkg.TC_QuickStockReceiptTest import QuickStockReceiptTest
from Test_StoreAdminFunctionalPkg.TC_QuickWastageEntryTest import QuickWastageEntryTest
from Test_StoreAdminFunctionalPkg.TC_SalesByCustomerReportTest import SalesByCustomerReportTest
from Test_StoreAdminFunctionalPkg.TC_SalesByPaymentModeReportTest import SalesByPaymentModeReportTest
from Test_StoreAdminFunctionalPkg.TC_SalesByProductCategoryTest import SalesByProductCategoryTest
from Test_StoreAdminFunctionalPkg.TC_SalesByProductReportTest import SalesByProductReportTest
from Test_StoreAdminFunctionalPkg.TC_SalesTaxReportTest import SalesTaxReportTest
from Test_StoreAdminFunctionalPkg.TC_StockAgingReportRetailTest import StockAgingReportRetailTest
from Test_StoreAdminFunctionalPkg.TC_StockLedgerReportTest import StockLedgerReportTest
from Test_StoreAdminFunctionalPkg.TC_StockMovementReportRetailTest import StockMovementReportRetailTest
from Test_StoreAdminFunctionalPkg.TC_StockPositionReportTest import StockPositionReportTest
from Test_StoreAdminFunctionalPkg.TC_SupplierStatementReportTest import SupplierStatementReportTest
from Test_StoreAdminFunctionalPkg.TC_TaxSummaryReportTest import TaxSummaryReportTest
from Test_StoreAdminFunctionalPkg.TC_WastageSummaryReportTest import WastageSummaryReportTest
import importlib